---
trailingComma: none
tabWidth: 4
printWidth: 120
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: avoid
semi: true
useTabs: false
jsxSingleQuote: false
quoteProps: as-needed
singleQuote: true
overrides:
    - files: ['**/*.json']
      options:
          tabWidth: 2
